name: Ultra-Perf Build
on:
  push:
    branches:
      - main
    paths:
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - '**.webp'
      - '!assets/optimized/**'  # Exclude optimized images from triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for git operations

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Generate HTML
        run: |
          pip install -r requirements.txt
          python generate_html.py

      - name: Prepare Deployment Branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout --orphan gh-pages
          git reset --hard
        # This creates a fresh gh-pages branch with no history, aligning with your reset strategy

      - name: Compress Images with Calibre
        id: calibre-optimization
        uses: calibreapp/image-actions@main
        continue-on-error: true
        with:
          githubToken: ${{ secrets.DEPLOY_TOKEN }}
          compressOnly: true
          jpegQuality: 80
          pngQuality: 80
          webpQuality: 80
          ignorePaths: node_modules/**
        # Removed unsupported inputs (convertToAvif, avifQuality, outputDir)

      - name: Debug Directory Contents (Post-Calibre)
        run: |
          ls -la assets/  # Check assets/ directory after Calibre
          ls -la assets/optimized/ || echo "assets/optimized/ not found"

      - name: Set up Node.js for Fallback
        if: steps.calibre-optimization.outcome == 'failure'
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Fallback Image Optimization
        if: steps.calibre-optimization.outcome == 'failure'
        run: |
          ls -la scripts/  # Debug: Verify optimize.js exists
          npm install sharp
          node scripts/optimize.js
        env:
          INPUT_DIR: assets/original
          OUTPUT_DIR: assets/optimized
        working-directory: ${{ github.workspace }}  # Root context

      - name: Debug Directory Contents (Post-Fallback)
        run: |
          ls -la assets/optimized/ || echo "assets/optimized/ still not found"

      - name: Commit and Deploy
        run: |
          git add -f assets/optimized index.html
          git commit -m "Deploy site" --allow-empty
          git remote set-url origin https://${{ secrets.DEPLOY_TOKEN }}@github.com/${{ github.repository }}.git
          git push origin gh-pages --force

      - name: Finalize Deployment
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_branch: gh-pages
          force_orphan: true  # Reinforces the orphan branch strategy

  lighthouse:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: treosh/lighthouse-ci-action@v3
        with:
          urls: |
            https://a1can0.github.io/a1can0.twitchstars.io/
          budgetPath: ./lighthouse-budget.json
          chromeFlags: |
            --no-sandbox
            --disable-dev-shm-usage