name: Ultra-Perf Build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Generate HTML
        run: |
          pip install -r requirements.txt
          python generate_html.py

      - name: Prepare Deployment Branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout --orphan gh-pages
          git reset --hard

      - name: Optimize Images
        run: |
          npm install sharp
          mkdir -p assets/optimized
          node scripts/optimize.js
        env:
          INPUT_DIR: assets/original
          OUTPUT_DIR: assets/optimized

      - name: Commit and Deploy
        run: |
          git add -f assets/optimized index.html
          git commit -m "Deploy site" --allow-empty
          git remote set-url origin https://${{ secrets.DEPLOY_TOKEN }}@github.com/${{ github.repository }}.git
          git push origin gh-pages --force

      - name: Verify Deployment
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_branch: gh-pages
          force_orphan: true

  lighthouse:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: treosh/lighthouse-ci-action@v3
        with:
          urls: |
            https://a1can0.github.io/a1can0.twitchstars.io/
          budgetPath: ./lighthouse-budget.json
          chromeFlags: |
            --no-sandbox
            --disable-dev-shm-usage