name: Lighthouse CI
on: [push]
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: treosh/lighthouse-ci-action@v3
        with:
          urls: |
            https://your-site.io/
          budgetPath: ./lighthouse-budget.json
